### ISSUE TITLE
1: Create FAISS vector database with UCI .txt files (webpage data)

### ISSUE THREAD

**Issue by AbhinandG** [DiyadotSaha/CourseBuddy#1]
1. Scrape .txt files from UCI catalogue and other webpages
2. Use DirectoryLoader class in LangChain to load the .txt files
3. Create FAISS vectorstore using the information from (2)

**Comment by AbhinandG** [comment]
https://python.langchain.com/docs/integrations/vectorstores/faiss/

**Comment by DiyadotSaha** [comment]
FAISS database created using hugging face
